name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t raghuprasadkonandur/myapp:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push raghuprasadkonandur/myapp:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_IP }} << 'EOF'
          if ! command -v docker &> /dev/null
          then
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
          else
            echo "Docker is already installed"
            if ! sudo systemctl is-active --quiet docker
            then
              sudo systemctl start docker
            else
              echo "Docker is already running"
            fi
          fi
          sudo docker pull raghuprasadkonandur/myapp:latest
          sudo docker run -d -p 80:5000 raghuprasadkonandur/myapp:latest
        EOF
